### ISSUE TITLE
AlunoDaoTest 

### ISSUE THREAD

**Issue by castrodeko11** [castrodeko11/Sistema-de-Judocas#4]
org.fpij.jitakyoei.model.dao > AlunoDaoTest

java.lang.NullPointerException
	at org.fpij.jitakyoei.model.beans.Aluno.hashCode(Aluno.java:43)
	at java.lang.Object.toString(Object.java:236)
	at java.lang.String.valueOf(String.java:2994)....

![image](https://user-images.githubusercontent.com/32251619/68553798-df3d3e80-0402-11ea-83f0-3726d0a9ce2a.png)

**Comment by lucasd19971113** [comment]
Execução do teste realizada com êxito e correção da classe de teste aluno.

org.fpij.jitakyoei.model.dao > AlunoDaoTest

![image](https://user-images.githubusercontent.com/32855908/68957861-abb73700-07a9-11ea-86b8-900b260d8018.png)
